events {}
http {
  upstream auth { server auth-service:8001; }
  upstream product { server product-service:8002; }
  upstream orders { server order-service:8003; }
  upstream payment { server payment-service:8004; }
  upstream notification { server notification-service:8005; }
  upstream profile { server profile-service:8006; }

  server {
    listen 80;
    location / { return 200 'SRE Microservices Demo is running
'; add_header Content-Type text/plain; }
    location /auth/ { proxy_pass http://auth/; }
    location /products/ { proxy_pass http://product/; }
    location /orders/ { proxy_pass http://orders/; }
    location /payments/ { proxy_pass http://payment/; }
    location /notifications/ { proxy_pass http://notification/; }
    location /profiles/ { proxy_pass http://profile/; }
  }
}
